### ISSUE TITLE
www/OPNProxy: "Access control" not working (with ssl inspection)

### ISSUE THREAD

**Issue by tomatotoast** [opnsense/plugins#4565]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
The "Access control" feature in the OPNProxy is only working in the policy test, but not with a proxy client.
Due to this issues any user can access anything in the web.

**To Reproduce**
Setup OPNproxy as described in the docs: https://docs.opnsense.org/manual/opnproxy.html
Generate a test blocking rule. It should not matter what you try to block in the test.
Check using the policy tester. It will tell you that your user is being blocked by your rule as intended.
Check using curl with proxy authentication. Blocking does not work. The request is logged in the access log of the proxy as usual. But it is not being blocked as it should.
excecute: `configctl opnproxy sync_users` or `configctl opnproxy apply_policies`. It doesnt help.

**Expected behavior**
squid should block the users request as configured.

**Screenshots**

Rule testing:

![Image](https://github.com/user-attachments/assets/a96c48da-0b7a-454c-83a2-cd281487f18b)

Testing with curl (this should not work due to the deny all rule):

![Image](https://github.com/user-attachments/assets/46fc8a5b-6094-4e3b-a5ec-c1bc82e0cf68)

Logfile after running curl:

![Image](https://github.com/user-attachments/assets/cfbfeff2-887d-48f0-abe5-e1ee089d1827)

Custom policy:
![Image](https://github.com/user-attachments/assets/723e5724-df63-4c7f-bd0d-00d06ab6d034)

![Image](https://github.com/user-attachments/assets/60546718-2818-4fd3-9d3e-19fc16348588)

**Relevant log files**
Squid log: 

/usr/local/sbin/squid -d9 -N -f /usr/local/etc/squid/squid.conf

`2025/02/28 22:44:15| Indexing cache entries: 32.18% (4000 out of 12431)
2025/02/28 22:44:15| Done reading /var/squid/cache swaplog (12430 entries)
2025/02/28 22:44:15| Finished rebuilding storage from disk.
      12430 Entries scanned
          0 Invalid entries
          0 With invalid flags
      12430 Objects loaded
          0 Objects expired
          0 Objects canceled
          0 Duplicate URLs purged
          0 Swapfile clashes avoided
    Took 0.02 seconds (601587.46 objects/sec).
2025/02/28 22:44:15| Beginning Validation Procedure
2025/02/28 22:44:15| Completed Validation Procedure
    Validated 12430 Entries
    store_swap_size = 19864905.50 KB
2025/02/28 22:44:16| storeLateRelease: released 0 objects
2025/02/28 22:44:19| Starting new external_acl_type helpers...
    current master transaction: master54
2025/02/28 22:44:19| helperOpenServers: Starting 1/5 'squid_acl_helper.py' processes
    current master transaction: master54
2025/02/28 22:44:19| ERROR: ALE missing IDENT
    current master transaction: master54
2025/02/28 22:44:19| ERROR: ALE missing IDENT
    current master transaction: master54
2025/02/28 22:44:20| ERROR: ALE missing IDENT
    current master transaction: master54
2025/02/28 22:44:20| ERROR: ALE missing IDENT
    current master transaction: master54
2025/02/28 22:44:40| ERROR: ALE missing IDENT
    current master transaction: master68
2025/02/28 22:44:40| ERROR: ALE missing IDENT
    current master transaction: master54
2025/02/28 22:44:40| ERROR: ALE missing IDENT
    current master transaction: master74
2025/02/28 22:44:41| ERROR: ALE missing IDENT
    current master transaction: master54
2025/02/28 22:46:06| ERROR: ALE missing IDENT
    current master transaction: master54
2025/02/28 22:46:06| ERROR: ALE missing IDENT
    current master transaction: master54
2025/02/28 22:46:06| ERROR: ALE missing IDENT
    current master transaction: master54
`

**Additional context**

`curl https://spiegel.de/ -k -U proxyuser:userpassword -x http://proxy.internal.domain.tld:3128 -L --proxy-anyauth`

**Environment**

Versions
OPNsense 25.1.2-amd64
FreeBSD 14.2-RELEASE-p2
OpenSSL 3.0.16

os-OPNProxy 1.0.5_1

**Comment by tomatotoast** [comment]
After doing some testing i discovered that blocking HTTP like: "http://opnsense.org/" works as expected. But HTTPs does not. For example "https://opnsense.org/", which also should be blocked by the "*" rule doesnt work. HTTPs content can be browsed.

**Comment by rac-HH** [comment]
You need SSL inspection:

Import a certificate in System: Trust: Authorities

In "Services: Squid Web Proxy: Administration / Forward Proxy" select:
* Enable SSL inspection
* Log SNI information only
* CA to use

For correct group evaluation in needed the fix from: [www/OPNProxy: "Access control" does not evaluate groups](https://github.com/opnsense/plugins/issues/4589)

**Comment by AdSchellevis** [comment]
should be fixed with https://github.com/tank0226/opnsense-plugins/commit/931f2c5d7a73f4158748fdf14c1a1f8ba3c5d20e as well then

**Comment by tomatotoast** [comment]
I have ssl inspection configured. And the ssl inspection is working. But the username doesn’t appear in the logs.

As you can see only in http the user shown. Not in Https:

![Image](https://github.com/user-attachments/assets/7b6fa261-cd46-4cbd-a56a-9c8614554922)

**Comment by tomatotoast** [comment]
@AdSchellevis 
I retested and yes, using SNI logging only the access control works.

But i use ssl inspection. All my clients have the CA installed. The SSL inspection itself works as expected.

Unfortunately the Access Control does not work when using ssl inspection as described in the documentation.

![Image](https://github.com/user-attachments/assets/0c264b1a-49f6-48cf-b0a5-b8fefb054907)

**Comment by tomatotoast** [comment]
This issue still exists in:

Versions
OPNsense 25.1.4_1-amd64
FreeBSD 14.2-RELEASE-p2
OpenSSL 3.0.16



Access Control does not work when using HTTPs Inspection. Do you need anything to solve this issue?

**Comment by tomatotoast** [comment]
Looks like this has been fixed with: OPNsense 25.1.6_4-amd64.

**Comment by pedrotecnico** [comment]
in version: OPNsense 25.7-amd64
Doesn't work.

**Comment by monk-insane** [comment]
This is still an issue in OPNsense 26.1.5-amd64

**Comment by fichtner** [comment]
The plugin is no longer maintained but we will consider merging PRs addressing this and other issues  https://github.com/opnsense/plugins/blob/8788b22a166fe257f2b87e083ba4a0bbc6f503f5/README.md?plain=1#L124
