### ISSUE TITLE
any change to make the fw_log.volt filter colors custom ?

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/plugins#912]
![grafik](https://user-images.githubusercontent.com/34602360/46905974-d9bdae00-cefb-11e8-9b37-a5896bd21917.png)

@fichtner 
it has "0" priority but I wanted to ask if we could make the colors custom? 
I think this is not quite suitable and it would not hurt to be able to customize this for the respective theme.

**Comment by AdSchellevis** [comment]
@opnsenseuser can you try to overwrite fw_pass and fw_block in your theme's? https://github.com/opnsense/core/commit/fe21186e05f5e33167cc109ce7fef09e3dc947b7 should fix the defaults.

**Comment by AdSchellevis** [comment]
@opnsenseuser by the way, tickets for core changes should be opened in the core repo, no need to reopen, but good to know for the next one :)

**Comment by opnsenseuser** [comment]
> 
> 
> @opnsenseuser by the way, tickets for core changes should be opened in the core repo, no need to reopen, but good to know for the next one :)

of course - sorry was my fault!

**Comment by AdSchellevis** [comment]
no problem :)

**Comment by opnsenseuser** [comment]
@AdSchellevis but problem still exists. no more logs are shown!
![grafik](https://user-images.githubusercontent.com/34602360/46907078-7e94b700-cf0d-11e8-91bd-d58fef5d4c92.png)

**Comment by opnsenseuser** [comment]
@AdSchellevis same problem on org. opnsense theme
![grafik](https://user-images.githubusercontent.com/34602360/46907213-7178c780-cf0f-11e8-8cfe-d7aec766f193.png)

**Comment by AdSchellevis** [comment]
any script errors? does it still show api calls in the network view? (and how do the responses look)
At my end it still works (using the new classes) an empty list kind of suggest other type of issues.

**Comment by opnsenseuser** [comment]
strange. even the original opnsense theme does not show anything. i try a restart of the vm.

**Comment by marjohn56** [comment]
Away for a long weekend, you'll need to remind me when I get back.
null

**Comment by opnsenseuser** [comment]
Ok

**Comment by opnsenseuser** [comment]
Not a big Deal. 
Add these two classes „fw_pass“ and „fw_block“ to your Template for the Firewall log as shown above. Give them background-Colors as you like and if you want change the content Main Color is i did.
2nd more important is the sidebar modifications as the Font-size of the Symbols, Text and the div widths for the submenu have changed a little. There where also Some things that arent relevant anymore. So you can delete them. Just compare my old and the new sidebar Main.css to See the difference.

If you need more help Message me
Regards rene

**Comment by opnsenseuser** [comment]
All changes accept the border-line between the main Menu items are also already in the Main.css of opnsense theme.

**Comment by opnsenseuser** [comment]
One more thing. For the Firewall log you do not need to modify anything if you still like the original colors. The org colors are hardcoded in the .volt file
